# -*- coding: utf-8 -*-
"""Hello world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EclBCP_MZD7FHlmjd1F4K04tQHSlSUdS
"""

print("Hello World")