name: Auto Commentv2
on: [issues, pull_request_target]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: 🚧　Install
        run: |
          yarn
      - name: 📦　Build
        run: |
          yarn build
      - uses: ./ # Ensure this points to the correct action path
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: >
            👋 @{{ author }}
            
            Thank you for raising an issue. We will investigate the matter and get back to you as soon as possible.
            
            Please make sure you have given us as much context as possible.
          pullRequestOpened: >
            👋 @{{ author }}
            
            Thank you for raising your pull request.
            
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
