name: Auto Comment
on: [issues, pull_request]
permissions: write-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1.1.2
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
             @{{ author }} Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
             Meanwhile if you want to work on this issue, Please raise the PR and we will review and merge it.
       
            👋 @{{ author }}
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
          pullRequestOpened: |
             @{{ author }} Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
             
          pullRequestUnlabeled: |
             @{{ author }} Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label to participate in the event.
          pullRequestSynchronize: |
             @{{ author }} Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label to participate in the event.
          pullRequestClosed: |
             @{{ author }} As your PR is closed now, Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label to participate in the event.
          pullRequestReopened: |
             @{{ author }} As your PR is closed now, Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label to participate in the event.
            👋 @{{ author }}
            Thank you for raising your pull request.
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible    